### PR TITLE
create a maintainers file

### PR DESCRIPTION
**Pull request by mawenzel**

### CODE REVIEW

**Comment by mawenzel** [comment]
👍

**Comment by alexeyklyukin** [comment]
👍

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
@alexeyklyukin @mawenzel you need to be public members of the Zalando organization in order to make Zappr approvals work. Please change your membership visibility here: https://github.com/orgs/zalando/people

**Comment by slitsche** [comment]
👍

**Comment by slitsche** [comment]
👍

**Pull request merged**
