### PR TITLE
Choose specified password when connecting

### PR DESCRIPTION
**Pull request by feikesteenbergen**
When specifying the password using the PGOBS_PASSWORD environment variable,
the frontend refuses to start:

```
KeyError: 'frontend_password'
```

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by LappleApple** [comment]
@a1exsh @slitsche This is now out of date, and before that needed 1/2 Zappr approvals. What's the plan? Please resolve it, thanks!

**Comment by LappleApple** [comment]
@a1exsh Pinging again ...

**Comment by avaczi** [comment]
:+1:

**Comment by LappleApple** [comment]
👍

**Pull request merged**
