### PR TITLE
Tidying up the README

### PR DESCRIPTION
**Pull request by LappleApple**

### CODE REVIEW

**Comment by slitsche** [comment]
👍

**Comment by LappleApple** [comment]
@a1exsh can you also approve so we can merge?

**Comment by a1exsh** [comment]
Looks good, thanks @LappleApple! :+1:

**Comment by a1exsh** [comment]
:+1:

**Comment by LappleApple** [comment]
Thanks, @slitsche @a1exsh! I can't merge the PR, can one of you guys do it?

**Comment by a1exsh** [comment]
Not yet, doesn't look like zappr has picked up the plus one from me (yet?)

**Comment by LappleApple** [comment]
@slitsche @a1exsh I think you guys have to approve on the same comment for this to get past Zappr :)

**Comment by a1exsh** [comment]
:+1:

**Pull request merged**
